### ISSUE TITLE
如果有类生成器的话，我可能会使用他

### ISSUE THREAD

**Issue by yzpopulation** [Kooboo/Json#2]
json有JsonCSharpClassGenerator作为类生成器，
你这个没有
![捕获](https://user-images.githubusercontent.com/12810531/59006816-6ab01380-8856-11e9-9b8b-f4b393e69483.PNG)
实际操作会遇到很多这样的问题
你这个默认类正确，不支持多余数据扔掉

**Comment by 1996v** [comment]
你应该曲解了类生成器的含义，你可以考虑使用dynamic作为类型标签。

**Comment by 1996v** [comment]
JsonSerializer.ToObject<dynamic>(str)
