### ISSUE TITLE
这个Json 工具有格式化Json 输出的功能吗？

### ISSUE THREAD

**Issue by hyzx86** [Kooboo/Json#5]
比如 这个：

`{
    "l1": {
        "l1_1": [
            "l1_1_1",
            "l1_1_2"
        ],
        "l1_2": {
            "l1_2_1": 121
        }
    },
    "l2": {
        "l2_1": null,
        "l2_2": true,
        "l2_3": {}
    }
}`

**Comment by hyzx86** [comment]
![image](https://user-images.githubusercontent.com/15613121/61449863-6bc17e00-a988-11e9-8559-480c9231eea8.png)

**Comment by 1996v** [comment]
没有...
