### ISSUE TITLE
能否增加反序列化带有json内容的文件，支持懒加载？

### ISSUE THREAD

**Issue by chilun555** [Kooboo/Json#6]
反序列化json文件时，能否根据key值名单不加载部分属性的数据，在需要的时候在根据key值从文件里拿出这部分数据？也就是懒加载

**Comment by 1996v** [comment]
星期1我将对反序列化出两个配置：1. 是否忽略源中与 model没有匹配的key对象  2. 根据字典来忽略指定的key对象

**Comment by 1996v** [comment]
已更新nuget
